run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gosec
    - gofmt
    - goimports
    - misspell
    - prealloc
    - unconvert
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/Beliashkoff/safe-garden-AI/backend
  revive:
    rules:
      - name: var-naming
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
