// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsers = `-- name: CountActiveUsers :one

SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

// Aggregates for the admin panel dashboard. All read-only. Day bucketing is
// pinned to UTC via date_trunc(field, ts, 'UTC') (PG14+) so it does not depend
// on the server session TimeZone and agrees with the Go-side UTC cutoffs.
func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFertilizerTapsSince = `-- name: CountFertilizerTapsSince :one
SELECT COUNT(*) FROM usage_log
WHERE endpoint LIKE 'fertilizer_tap:%' AND created_at >= $1
`

func (q *Queries) CountFertilizerTapsSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countFertilizerTapsSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMessages = `-- name: CountUserMessages :one
SELECT COUNT(*) FROM messages WHERE role = 'user'
`

func (q *Queries) CountUserMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMessagesSince = `-- name: CountUserMessagesSince :one
SELECT COUNT(*) FROM messages WHERE role = 'user' AND created_at >= $1
`

func (q *Queries) CountUserMessagesSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMessagesSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedSince = `-- name: CountUsersCreatedSince :one
SELECT COUNT(*) FROM users WHERE created_at >= $1
`

func (q *Queries) CountUsersCreatedSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersCreatedSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const messagesByDay = `-- name: MessagesByDay :many
SELECT date_trunc('day', created_at, 'UTC')::timestamptz AS day, COUNT(*) AS count
FROM messages
WHERE role = 'user' AND created_at >= $1
GROUP BY 1
ORDER BY 1
`

type MessagesByDayRow struct {
	Day   pgtype.Timestamptz
	Count int64
}

func (q *Queries) MessagesByDay(ctx context.Context, createdAt pgtype.Timestamptz) ([]MessagesByDayRow, error) {
	rows, err := q.db.Query(ctx, messagesByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesByDayRow
	for rows.Next() {
		var i MessagesByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUsageSince = `-- name: SumUsageSince :one
SELECT
    COALESCE(SUM(tokens_in), 0)::bigint    AS tokens_in,
    COALESCE(SUM(tokens_out), 0)::bigint   AS tokens_out,
    COALESCE(SUM(cost_usd), 0)::numeric    AS cost_usd
FROM usage_log
WHERE created_at >= $1 AND endpoint NOT LIKE 'fertilizer_tap:%'
`

type SumUsageSinceRow struct {
	TokensIn  int64
	TokensOut int64
	CostUsd   pgtype.Numeric
}

func (q *Queries) SumUsageSince(ctx context.Context, createdAt pgtype.Timestamptz) (SumUsageSinceRow, error) {
	row := q.db.QueryRow(ctx, sumUsageSince, createdAt)
	var i SumUsageSinceRow
	err := row.Scan(&i.TokensIn, &i.TokensOut, &i.CostUsd)
	return i, err
}

const topFertilizerTaps = `-- name: TopFertilizerTaps :many
SELECT split_part(endpoint, ':', 2) AS slug, COUNT(*) AS taps
FROM usage_log
WHERE endpoint LIKE 'fertilizer_tap:%' AND created_at >= $1
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
`

type TopFertilizerTapsRow struct {
	Slug string
	Taps int64
}

func (q *Queries) TopFertilizerTaps(ctx context.Context, createdAt pgtype.Timestamptz) ([]TopFertilizerTapsRow, error) {
	rows, err := q.db.Query(ctx, topFertilizerTaps, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopFertilizerTapsRow
	for rows.Next() {
		var i TopFertilizerTapsRow
		if err := rows.Scan(&i.Slug, &i.Taps); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageByDay = `-- name: UsageByDay :many
SELECT
    date_trunc('day', created_at, 'UTC')::timestamptz AS day,
    COALESCE(SUM(tokens_in), 0)::bigint             AS tokens_in,
    COALESCE(SUM(tokens_out), 0)::bigint            AS tokens_out,
    COALESCE(SUM(cost_usd), 0)::numeric             AS cost_usd
FROM usage_log
WHERE created_at >= $1 AND endpoint NOT LIKE 'fertilizer_tap:%'
GROUP BY 1
ORDER BY 1
`

type UsageByDayRow struct {
	Day       pgtype.Timestamptz
	TokensIn  int64
	TokensOut int64
	CostUsd   pgtype.Numeric
}

func (q *Queries) UsageByDay(ctx context.Context, createdAt pgtype.Timestamptz) ([]UsageByDayRow, error) {
	rows, err := q.db.Query(ctx, usageByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageByDayRow
	for rows.Next() {
		var i UsageByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersByDay = `-- name: UsersByDay :many
SELECT date_trunc('day', created_at, 'UTC')::timestamptz AS day, COUNT(*) AS count
FROM users
WHERE created_at >= $1
GROUP BY 1
ORDER BY 1
`

type UsersByDayRow struct {
	Day   pgtype.Timestamptz
	Count int64
}

func (q *Queries) UsersByDay(ctx context.Context, createdAt pgtype.Timestamptz) ([]UsersByDayRow, error) {
	rows, err := q.db.Query(ctx, usersByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersByDayRow
	for rows.Next() {
		var i UsersByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
