// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_stats.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activationSince = `-- name: ActivationSince :one

WITH firstmsg AS (
    SELECT user_id, MIN(created_at) AS first_at
    FROM messages
    WHERE role = 'user'
    GROUP BY user_id
)
SELECT
    COUNT(*)::bigint        AS signups,
    COUNT(f.user_id)::bigint AS activated,
    COALESCE(EXTRACT(EPOCH FROM percentile_cont(0.5) WITHIN GROUP (
        ORDER BY (f.first_at - u.created_at)
    )), 0)::float8          AS median_seconds
FROM users u
LEFT JOIN firstmsg f ON f.user_id = u.id
WHERE u.created_at >= $1 AND u.deleted_at IS NULL
`

type ActivationSinceRow struct {
	Signups       int64
	Activated     int64
	MedianSeconds float64
}

// ============================================================================
// Growth analytics (продуктовая аналитика). All read-only over existing tables.
// ============================================================================
// Activation proxy: of users registered in the window, how many asked at least
// one question, and the median delay from sign-up to that first question. Note:
// the SPEC §1.4 KPI is "photo in the first session"; input type of the first
// session is not flagged in the schema, so this approximates with "first question".
func (q *Queries) ActivationSince(ctx context.Context, createdAt pgtype.Timestamptz) (ActivationSinceRow, error) {
	row := q.db.QueryRow(ctx, activationSince, createdAt)
	var i ActivationSinceRow
	err := row.Scan(&i.Signups, &i.Activated, &i.MedianSeconds)
	return i, err
}

const activeUserWindows = `-- name: ActiveUserWindows :one
SELECT
    COUNT(DISTINCT user_id) FILTER (WHERE created_at >= $1)::bigint  AS dau,
    COUNT(DISTINCT user_id) FILTER (WHERE created_at >= $2)::bigint AS wau,
    COUNT(DISTINCT user_id)::bigint                                          AS mau
FROM messages
WHERE role = 'user' AND created_at >= $3
`

type ActiveUserWindowsParams struct {
	DaySince   pgtype.Timestamptz
	WeekSince  pgtype.Timestamptz
	MonthSince pgtype.Timestamptz
}

type ActiveUserWindowsRow struct {
	Dau int64
	Wau int64
	Mau int64
}

// DAU/WAU/MAU: distinct users who sent a message inside each trailing window.
// All three read the same 30-day scan; the narrower windows are FILTERed.
func (q *Queries) ActiveUserWindows(ctx context.Context, arg ActiveUserWindowsParams) (ActiveUserWindowsRow, error) {
	row := q.db.QueryRow(ctx, activeUserWindows, arg.DaySince, arg.WeekSince, arg.MonthSince)
	var i ActiveUserWindowsRow
	err := row.Scan(&i.Dau, &i.Wau, &i.Mau)
	return i, err
}

const activityByWeekSince = `-- name: ActivityByWeekSince :many
SELECT
    date_trunc('week', created_at, 'UTC')::timestamptz           AS week,
    COUNT(*) FILTER (WHERE role = 'user')::bigint                AS messages,
    COUNT(DISTINCT user_id) FILTER (WHERE role = 'user')::bigint AS active_users
FROM messages
WHERE created_at >= $1
GROUP BY 1
ORDER BY 1
`

type ActivityByWeekSinceRow struct {
	Week        pgtype.Timestamptz
	Messages    int64
	ActiveUsers int64
}

// Weekly seasonal curve over a long horizon: questions and active users.
func (q *Queries) ActivityByWeekSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]ActivityByWeekSinceRow, error) {
	rows, err := q.db.Query(ctx, activityByWeekSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityByWeekSinceRow
	for rows.Next() {
		var i ActivityByWeekSinceRow
		if err := rows.Scan(&i.Week, &i.Messages, &i.ActiveUsers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activityHeatmapSince = `-- name: ActivityHeatmapSince :many
SELECT
    EXTRACT(DOW  FROM created_at AT TIME ZONE 'Europe/Moscow')::int AS dow,
    EXTRACT(HOUR FROM created_at AT TIME ZONE 'Europe/Moscow')::int AS hour,
    COUNT(*)::bigint                                                AS count
FROM messages
WHERE role = 'user' AND created_at >= $1
GROUP BY 1, 2
ORDER BY 1, 2
`

type ActivityHeatmapSinceRow struct {
	Dow   int32
	Hour  int32
	Count int64
}

// Question volume by Moscow day-of-week (0=Sun..6=Sat) and hour-of-day.
func (q *Queries) ActivityHeatmapSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]ActivityHeatmapSinceRow, error) {
	rows, err := q.db.Query(ctx, activityHeatmapSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityHeatmapSinceRow
	for rows.Next() {
		var i ActivityHeatmapSinceRow
		if err := rows.Scan(&i.Dow, &i.Hour, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cacheStatsSince = `-- name: CacheStatsSince :one
SELECT
    COALESCE(SUM(input_uncached_tokens), 0)::bigint              AS input_uncached,
    COALESCE(SUM(cache_write_tokens), 0)::bigint                 AS cache_write,
    COALESCE(SUM(cache_read_tokens), 0)::bigint                  AS cache_read,
    COUNT(*) FILTER (WHERE cache_read_tokens IS NOT NULL)::bigint AS rows_with_data
FROM usage_log
WHERE created_at >= $1 AND endpoint = '/v1/messages'
`

type CacheStatsSinceRow struct {
	InputUncached int64
	CacheWrite    int64
	CacheRead     int64
	RowsWithData  int64
}

// Only rows written after migration 0017 carry the cache split; older rows have
// NULLs and are excluded from the denominator via rows_with_data.
func (q *Queries) CacheStatsSince(ctx context.Context, createdAt pgtype.Timestamptz) (CacheStatsSinceRow, error) {
	row := q.db.QueryRow(ctx, cacheStatsSince, createdAt)
	var i CacheStatsSinceRow
	err := row.Scan(
		&i.InputUncached,
		&i.CacheWrite,
		&i.CacheRead,
		&i.RowsWithData,
	)
	return i, err
}

const cardImpressionsBySlugSince = `-- name: CardImpressionsBySlugSince :many
SELECT (p->>'slug')::text AS slug, COUNT(*)::bigint AS impressions
FROM message_blocks mb,
     LATERAL jsonb_array_elements(mb.metadata->'products') AS p
WHERE mb.type = 'fertilizer_card' AND mb.created_at >= $1
GROUP BY 1
`

type CardImpressionsBySlugSinceRow struct {
	Slug        string
	Impressions int64
}

// Per-slug impressions from the {"products":[{"slug":...}]} card metadata.
func (q *Queries) CardImpressionsBySlugSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]CardImpressionsBySlugSinceRow, error) {
	rows, err := q.db.Query(ctx, cardImpressionsBySlugSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardImpressionsBySlugSinceRow
	for rows.Next() {
		var i CardImpressionsBySlugSinceRow
		if err := rows.Scan(&i.Slug, &i.Impressions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cardImpressionsSince = `-- name: CardImpressionsSince :one

SELECT COUNT(*)::bigint AS impressions
FROM message_blocks
WHERE type = 'fertilizer_card' AND created_at >= $1
`

// ============================================================================
// Answer quality (качество ответов и обратная связь).
// ============================================================================
func (q *Queries) CardImpressionsSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, cardImpressionsSince, createdAt)
	var impressions int64
	err := row.Scan(&impressions)
	return impressions, err
}

const catalogPerformanceSince = `-- name: CatalogPerformanceSince :many
WITH imp AS (
    SELECT (p->>'slug')::text AS slug, COUNT(*)::bigint AS impressions
    FROM message_blocks mb, LATERAL jsonb_array_elements(mb.metadata->'products') AS p
    WHERE mb.type = 'fertilizer_card' AND mb.created_at >= $1
    GROUP BY 1
),
taps AS (
    SELECT split_part(endpoint, ':', 2) AS slug, COUNT(*)::bigint AS taps
    FROM usage_log
    WHERE endpoint LIKE 'fertilizer_tap:%' AND created_at >= $1
    GROUP BY 1
)
SELECT
    f.slug,
    f.name,
    COALESCE(imp.impressions, 0)::bigint AS impressions,
    COALESCE(taps.taps, 0)::bigint       AS taps
FROM fertilizers f
LEFT JOIN imp ON imp.slug = f.slug
LEFT JOIN taps ON taps.slug = f.slug
WHERE f.active = TRUE
ORDER BY impressions DESC, taps DESC, f.name
`

type CatalogPerformanceSinceRow struct {
	Slug        string
	Name        string
	Impressions int64
	Taps        int64
}

// Every ACTIVE catalog product with its impressions (card shows) and taps over
// the window. Products with 0/0 are dead assortment. Impressions come from the
// fertilizer_card block metadata; taps from usage_log.
func (q *Queries) CatalogPerformanceSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]CatalogPerformanceSinceRow, error) {
	rows, err := q.db.Query(ctx, catalogPerformanceSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogPerformanceSinceRow
	for rows.Next() {
		var i CatalogPerformanceSinceRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Impressions,
			&i.Taps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conversationDepthSince = `-- name: ConversationDepthSince :one
WITH per_user AS (
    SELECT user_id, COUNT(*) AS msgs
    FROM messages
    WHERE role = 'user' AND created_at >= $1
    GROUP BY user_id
)
SELECT
    COUNT(*) FILTER (WHERE msgs = 1)::bigint             AS bucket1,
    COUNT(*) FILTER (WHERE msgs BETWEEN 2 AND 4)::bigint AS bucket2_4,
    COUNT(*) FILTER (WHERE msgs BETWEEN 5 AND 9)::bigint AS bucket5_9,
    COUNT(*) FILTER (WHERE msgs >= 10)::bigint           AS bucket10,
    COALESCE(AVG(msgs), 0)::float8                                          AS avg_msgs,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY msgs), 0)::float8  AS median_msgs,
    COALESCE(percentile_cont(0.9) WITHIN GROUP (ORDER BY msgs), 0)::float8  AS p90_msgs
FROM per_user
`

type ConversationDepthSinceRow struct {
	Bucket1    int64
	Bucket24   int64
	Bucket59   int64
	Bucket10   int64
	AvgMsgs    float64
	MedianMsgs float64
	P90Msgs    float64
}

// Distribution of question count per active user plus avg/median/p90.
func (q *Queries) ConversationDepthSince(ctx context.Context, createdAt pgtype.Timestamptz) (ConversationDepthSinceRow, error) {
	row := q.db.QueryRow(ctx, conversationDepthSince, createdAt)
	var i ConversationDepthSinceRow
	err := row.Scan(
		&i.Bucket1,
		&i.Bucket24,
		&i.Bucket59,
		&i.Bucket10,
		&i.AvgMsgs,
		&i.MedianMsgs,
		&i.P90Msgs,
	)
	return i, err
}

const conversationsWithNegativeFeedbackSince = `-- name: ConversationsWithNegativeFeedbackSince :many
SELECT
    m.conversation_id,
    COUNT(*)::bigint               AS downs,
    MAX(f.updated_at)::timestamptz AS last_down
FROM message_feedback f
JOIN messages m ON m.id = f.message_id
WHERE f.value = 'down' AND f.updated_at >= $1
GROUP BY m.conversation_id
HAVING COUNT(*) >= $2
ORDER BY downs DESC, last_down DESC
LIMIT 50
`

type ConversationsWithNegativeFeedbackSinceParams struct {
	Since    pgtype.Timestamptz
	MinDowns interface{}
}

type ConversationsWithNegativeFeedbackSinceRow struct {
	ConversationID uuid.UUID
	Downs          int64
	LastDown       pgtype.Timestamptz
}

// Chats accumulating dislikes (1 chat per user in v1, so this flags unhappy users).
func (q *Queries) ConversationsWithNegativeFeedbackSince(ctx context.Context, arg ConversationsWithNegativeFeedbackSinceParams) ([]ConversationsWithNegativeFeedbackSinceRow, error) {
	rows, err := q.db.Query(ctx, conversationsWithNegativeFeedbackSince, arg.Since, arg.MinDowns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationsWithNegativeFeedbackSinceRow
	for rows.Next() {
		var i ConversationsWithNegativeFeedbackSinceRow
		if err := rows.Scan(&i.ConversationID, &i.Downs, &i.LastDown); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costByKindSince = `-- name: CostByKindSince :one
SELECT
    COALESCE(SUM(cost_usd) FILTER (WHERE endpoint = '/v1/messages'), 0)::numeric AS claude_cost,
    COUNT(*) FILTER (WHERE endpoint = '/v1/messages')::bigint                    AS claude_calls,
    COUNT(*) FILTER (WHERE endpoint LIKE 'fertilizer_tap:%')::bigint             AS taps,
    COUNT(*) FILTER (WHERE endpoint = 'transcribe')::bigint                      AS transcriptions,
    COALESCE(SUM(duration_ms) FILTER (WHERE endpoint = 'transcribe'), 0)::bigint AS transcribe_ms
FROM usage_log
WHERE created_at >= $1
`

type CostByKindSinceRow struct {
	ClaudeCost     pgtype.Numeric
	ClaudeCalls    int64
	Taps           int64
	Transcriptions int64
	TranscribeMs   int64
}

func (q *Queries) CostByKindSince(ctx context.Context, createdAt pgtype.Timestamptz) (CostByKindSinceRow, error) {
	row := q.db.QueryRow(ctx, costByKindSince, createdAt)
	var i CostByKindSinceRow
	err := row.Scan(
		&i.ClaudeCost,
		&i.ClaudeCalls,
		&i.Taps,
		&i.Transcriptions,
		&i.TranscribeMs,
	)
	return i, err
}

const costByModelSince = `-- name: CostByModelSince :many
SELECT
    COALESCE(model, 'до версионирования')::text AS model,
    COALESCE(SUM(cost_usd), 0)::numeric         AS cost_usd,
    COALESCE(SUM(tokens_in), 0)::bigint         AS tokens_in,
    COALESCE(SUM(tokens_out), 0)::bigint        AS tokens_out,
    COUNT(*)::bigint                            AS requests
FROM usage_log
WHERE created_at >= $1 AND endpoint = '/v1/messages'
GROUP BY 1
ORDER BY 2 DESC
`

type CostByModelSinceRow struct {
	Model     string
	CostUsd   pgtype.Numeric
	TokensIn  int64
	TokensOut int64
	Requests  int64
}

func (q *Queries) CostByModelSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]CostByModelSinceRow, error) {
	rows, err := q.db.Query(ctx, costByModelSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostByModelSinceRow
	for rows.Next() {
		var i CostByModelSinceRow
		if err := rows.Scan(
			&i.Model,
			&i.CostUsd,
			&i.TokensIn,
			&i.TokensOut,
			&i.Requests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveUsers = `-- name: CountActiveUsers :one

SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

// Aggregates for the admin panel dashboard. All read-only. Day bucketing is
// pinned to UTC via date_trunc(field, ts, 'UTC') (PG14+) so it does not depend
// on the server session TimeZone and agrees with the Go-side UTC cutoffs.
func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFertilizerTapsSince = `-- name: CountFertilizerTapsSince :one
SELECT COUNT(*) FROM usage_log
WHERE endpoint LIKE 'fertilizer_tap:%' AND created_at >= $1
`

func (q *Queries) CountFertilizerTapsSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countFertilizerTapsSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMessages = `-- name: CountUserMessages :one
SELECT COUNT(*) FROM messages WHERE role = 'user'
`

func (q *Queries) CountUserMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMessagesSince = `-- name: CountUserMessagesSince :one
SELECT COUNT(*) FROM messages WHERE role = 'user' AND created_at >= $1
`

func (q *Queries) CountUserMessagesSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMessagesSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedSince = `-- name: CountUsersCreatedSince :one
SELECT COUNT(*) FROM users WHERE created_at >= $1
`

func (q *Queries) CountUsersCreatedSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersCreatedSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const errorsByDaySince = `-- name: ErrorsByDaySince :many
SELECT date_trunc('day', created_at, 'UTC')::timestamptz AS day, COUNT(*)::bigint AS count
FROM admin_error_events
WHERE created_at >= $1
GROUP BY 1
ORDER BY 1
`

type ErrorsByDaySinceRow struct {
	Day   pgtype.Timestamptz
	Count int64
}

func (q *Queries) ErrorsByDaySince(ctx context.Context, createdAt pgtype.Timestamptz) ([]ErrorsByDaySinceRow, error) {
	rows, err := q.db.Query(ctx, errorsByDaySince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErrorsByDaySinceRow
	for rows.Next() {
		var i ErrorsByDaySinceRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const errorsByRouteSince = `-- name: ErrorsByRouteSince :many
SELECT route, status, COUNT(*)::bigint AS count
FROM admin_error_events
WHERE created_at >= $1
GROUP BY route, status
ORDER BY count DESC
LIMIT 20
`

type ErrorsByRouteSinceRow struct {
	Route  string
	Status int32
	Count  int64
}

func (q *Queries) ErrorsByRouteSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]ErrorsByRouteSinceRow, error) {
	rows, err := q.db.Query(ctx, errorsByRouteSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErrorsByRouteSinceRow
	for rows.Next() {
		var i ErrorsByRouteSinceRow
		if err := rows.Scan(&i.Route, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failCodesSince = `-- name: FailCodesSince :many
SELECT COALESCE(fail_code, 'unknown')::text AS fail_code, COUNT(*)::bigint AS count
FROM messages
WHERE role = 'assistant' AND status = 'failed' AND created_at >= $1
GROUP BY 1
ORDER BY 2 DESC
`

type FailCodesSinceRow struct {
	FailCode string
	Count    int64
}

// Breakdown of failed assistant turns by reason for the reliability widget.
func (q *Queries) FailCodesSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]FailCodesSinceRow, error) {
	rows, err := q.db.Query(ctx, failCodesSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailCodesSinceRow
	for rows.Next() {
		var i FailCodesSinceRow
		if err := rows.Scan(&i.FailCode, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feedbackByDay = `-- name: FeedbackByDay :many
SELECT
    date_trunc('day', created_at, 'UTC')::timestamptz AS day,
    COUNT(*) FILTER (WHERE value = 'up')::bigint      AS up,
    COUNT(*) FILTER (WHERE value = 'down')::bigint    AS down
FROM message_feedback
WHERE created_at >= $1
GROUP BY 1
ORDER BY 1
`

type FeedbackByDayRow struct {
	Day  pgtype.Timestamptz
	Up   int64
	Down int64
}

func (q *Queries) FeedbackByDay(ctx context.Context, createdAt pgtype.Timestamptz) ([]FeedbackByDayRow, error) {
	rows, err := q.db.Query(ctx, feedbackByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackByDayRow
	for rows.Next() {
		var i FeedbackByDayRow
		if err := rows.Scan(&i.Day, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feedbackTotalsSince = `-- name: FeedbackTotalsSince :one
SELECT
    COUNT(*) FILTER (WHERE value = 'up')::bigint   AS up,
    COUNT(*) FILTER (WHERE value = 'down')::bigint AS down
FROM message_feedback
WHERE created_at >= $1
`

type FeedbackTotalsSinceRow struct {
	Up   int64
	Down int64
}

// One verdict per (message, user), so up+down equals the number of rated answers.
func (q *Queries) FeedbackTotalsSince(ctx context.Context, createdAt pgtype.Timestamptz) (FeedbackTotalsSinceRow, error) {
	row := q.db.QueryRow(ctx, feedbackTotalsSince, createdAt)
	var i FeedbackTotalsSinceRow
	err := row.Scan(&i.Up, &i.Down)
	return i, err
}

const followupRateSince = `-- name: FollowupRateSince :one
WITH seq AS (
    SELECT
        m.role,
        m.created_at,
        LEAD(m.role)       OVER w AS next_role,
        LEAD(m.created_at) OVER w AS next_at
    FROM messages m
    WHERE m.created_at >= $1 AND m.role IN ('user', 'assistant')
    WINDOW w AS (PARTITION BY m.conversation_id ORDER BY m.created_at)
)
SELECT
    COUNT(*) FILTER (WHERE role = 'assistant')::bigint AS answers,
    COUNT(*) FILTER (
        WHERE role = 'assistant'
          AND next_role = 'user'
          AND next_at <= created_at + interval '5 minutes'
    )::bigint AS followups
FROM seq
`

type FollowupRateSinceRow struct {
	Answers   int64
	Followups int64
}

// Implicit dissatisfaction proxy: share of assistant answers immediately followed
// by another user message within 5 minutes (the user had to re-ask).
func (q *Queries) FollowupRateSince(ctx context.Context, createdAt pgtype.Timestamptz) (FollowupRateSinceRow, error) {
	row := q.db.QueryRow(ctx, followupRateSince, createdAt)
	var i FollowupRateSinceRow
	err := row.Scan(&i.Answers, &i.Followups)
	return i, err
}

const getDeletionPipeline = `-- name: GetDeletionPipeline :one
SELECT
    COUNT(*) FILTER (WHERE deleted_at IS NOT NULL)::bigint                             AS deleted_total,
    COUNT(*) FILTER (WHERE deleted_at IS NOT NULL AND media_purged_at IS NULL)::bigint AS purge_pending,
    COALESCE(
        EXTRACT(EPOCH FROM (NOW() - MIN(deleted_at) FILTER (WHERE media_purged_at IS NULL))) / 3600,
        0
    )::float8 AS oldest_pending_hours
FROM users
`

type GetDeletionPipelineRow struct {
	DeletedTotal       int64
	PurgePending       int64
	OldestPendingHours float64
}

// Account-deletion -> media-purge pipeline health. oldest_pending_hours surfaces a
// stalled cleanup cron (deleted but Object Storage prefix not yet wiped).
func (q *Queries) GetDeletionPipeline(ctx context.Context) (GetDeletionPipelineRow, error) {
	row := q.db.QueryRow(ctx, getDeletionPipeline)
	var i GetDeletionPipelineRow
	err := row.Scan(&i.DeletedTotal, &i.PurgePending, &i.OldestPendingHours)
	return i, err
}

const getLastCleanupRun = `-- name: GetLastCleanupRun :one
SELECT created_at, details FROM admin_audit_log
WHERE action = 'cleanup_run'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastCleanupRunRow struct {
	CreatedAt pgtype.Timestamptz
	Details   []byte
}

func (q *Queries) GetLastCleanupRun(ctx context.Context) (GetLastCleanupRunRow, error) {
	row := q.db.QueryRow(ctx, getLastCleanupRun)
	var i GetLastCleanupRunRow
	err := row.Scan(&i.CreatedAt, &i.Details)
	return i, err
}

const inputTypeByDaySince = `-- name: InputTypeByDaySince :many
SELECT
    date_trunc('day', m.created_at, 'UTC')::timestamptz AS day,
    COUNT(*) FILTER (WHERE EXISTS (SELECT 1 FROM message_blocks b WHERE b.message_id = m.id AND b.type = 'image'))::bigint AS photo,
    COUNT(*) FILTER (WHERE EXISTS (SELECT 1 FROM message_blocks b WHERE b.message_id = m.id AND b.type = 'audio'))::bigint AS voice,
    COUNT(*)::bigint AS total
FROM messages m
WHERE m.role = 'user' AND m.created_at >= $1
GROUP BY 1
ORDER BY 1
`

type InputTypeByDaySinceRow struct {
	Day   pgtype.Timestamptz
	Photo int64
	Voice int64
	Total int64
}

func (q *Queries) InputTypeByDaySince(ctx context.Context, createdAt pgtype.Timestamptz) ([]InputTypeByDaySinceRow, error) {
	rows, err := q.db.Query(ctx, inputTypeByDaySince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InputTypeByDaySinceRow
	for rows.Next() {
		var i InputTypeByDaySinceRow
		if err := rows.Scan(
			&i.Day,
			&i.Photo,
			&i.Voice,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCleanupRun = `-- name: InsertCleanupRun :exec
INSERT INTO admin_audit_log (action, details) VALUES ('cleanup_run', $1)
`

// Heartbeat written by the cleanup cron at the end of each run; details is the
// JSONB count summary. No PII (counts only).
func (q *Queries) InsertCleanupRun(ctx context.Context, details []byte) error {
	_, err := q.db.Exec(ctx, insertCleanupRun, details)
	return err
}

const listDeletionEvents = `-- name: ListDeletionEvents :many

SELECT id, user_id, action, created_at
FROM audit_log
WHERE action IN ('account_deleted', 'account_media_purged') AND user_id IS NOT NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDeletionEventsParams struct {
	Limit  int32
	Offset int32
}

type ListDeletionEventsRow struct {
	ID        int64
	UserID    pgtype.UUID
	Action    string
	CreatedAt pgtype.Timestamptz
}

// ============================================================================
// Data lifecycle & compliance (152-FZ / 406-FZ). user/conversation ids masked in
// the usecase before leaving the backend.
// ============================================================================
// Erasure proof: account deletion + media purge events, newest first. Paired by
// masked user id in the UI (deleted -> purged).
func (q *Queries) ListDeletionEvents(ctx context.Context, arg ListDeletionEventsParams) ([]ListDeletionEventsRow, error) {
	rows, err := q.db.Query(ctx, listDeletionEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletionEventsRow
	for rows.Next() {
		var i ListDeletionEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownvotedMessages = `-- name: ListDownvotedMessages :many
SELECT
    f.message_id,
    f.updated_at,
    m.conversation_id,
    (SELECT mb.content_text FROM message_blocks mb
        WHERE mb.message_id = m.id AND mb.type = 'text'
        ORDER BY mb.order_index LIMIT 1) AS answer_text,
    (SELECT mb.content_text
        FROM messages um
        JOIN message_blocks mb ON mb.message_id = um.id AND mb.type = 'text'
        WHERE um.conversation_id = m.conversation_id
          AND um.role = 'user' AND um.created_at < m.created_at
        ORDER BY um.created_at DESC, mb.order_index LIMIT 1) AS question_text,
    EXISTS (SELECT 1 FROM message_blocks mb
        WHERE mb.message_id = m.id AND mb.type = 'fertilizer_card') AS had_card
FROM message_feedback f
JOIN messages m ON m.id = f.message_id
WHERE f.value = 'down'
ORDER BY f.updated_at DESC
LIMIT $1 OFFSET $2
`

type ListDownvotedMessagesParams struct {
	Limit  int32
	Offset int32
}

type ListDownvotedMessagesRow struct {
	MessageID      uuid.UUID
	UpdatedAt      pgtype.Timestamptz
	ConversationID uuid.UUID
	AnswerText     pgtype.Text
	QuestionText   pgtype.Text
	HadCard        bool
}

// Feed of disliked answers for the operator-agronomist to review. Returns message
// CONTENT (question + answer text): this is a per-request read into the
// authenticated panel, NOT a log — callers must never write it to slog/Sentry
// (CLAUDE.md invariant #3).
func (q *Queries) ListDownvotedMessages(ctx context.Context, arg ListDownvotedMessagesParams) ([]ListDownvotedMessagesRow, error) {
	rows, err := q.db.Query(ctx, listDownvotedMessages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDownvotedMessagesRow
	for rows.Next() {
		var i ListDownvotedMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.UpdatedAt,
			&i.ConversationID,
			&i.AnswerText,
			&i.QuestionText,
			&i.HadCard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurityEvents = `-- name: ListSecurityEvents :many

SELECT id, user_id, action, ip, created_at
FROM audit_log
WHERE action IN ('refresh_reuse_detected', 'account_deleted', 'account_media_purged')
  AND user_id IS NOT NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSecurityEventsParams struct {
	Limit  int32
	Offset int32
}

type ListSecurityEventsRow struct {
	ID        int64
	UserID    pgtype.UUID
	Action    string
	Ip        *netip.Addr
	CreatedAt pgtype.Timestamptz
}

// ============================================================================
// Security & abuse. user_id/email are masked in the usecase before leaving the
// backend (CLAUDE.md invariant #3); these queries return the raw values only
// across the storage boundary.
// ============================================================================
// High-signal user security events (session hijack attempts, deletions). Logins
// are excluded here (aggregated separately on the dashboard) to keep the feed
// actionable. Allowlist is fixed, not caller-supplied.
func (q *Queries) ListSecurityEvents(ctx context.Context, arg ListSecurityEventsParams) ([]ListSecurityEventsRow, error) {
	rows, err := q.db.Query(ctx, listSecurityEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecurityEventsRow
	for rows.Next() {
		var i ListSecurityEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePurges = `-- name: ListStalePurges :many
SELECT id, deleted_at, (EXTRACT(EPOCH FROM (NOW() - deleted_at)) / 3600)::float8 AS pending_hours
FROM users
WHERE deleted_at IS NOT NULL AND media_purged_at IS NULL AND deleted_at < $1
ORDER BY deleted_at
LIMIT 100
`

type ListStalePurgesRow struct {
	ID           uuid.UUID
	DeletedAt    pgtype.Timestamptz
	PendingHours float64
}

// Deleted accounts whose Object Storage media has not been purged past the SLA
// cutoff (drill-down for the deletion-pipeline backlog).
func (q *Queries) ListStalePurges(ctx context.Context, deletedAt pgtype.Timestamptz) ([]ListStalePurgesRow, error) {
	rows, err := q.db.Query(ctx, listStalePurges, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStalePurgesRow
	for rows.Next() {
		var i ListStalePurgesRow
		if err := rows.Scan(&i.ID, &i.DeletedAt, &i.PendingHours); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginsByProviderSince = `-- name: LoginsByProviderSince :many
SELECT action, COUNT(*)::bigint AS logins, COUNT(DISTINCT user_id)::bigint AS users
FROM audit_log
WHERE action IN ('sign_in_yandex', 'sign_in_vk', 'sign_in_email') AND created_at >= $1
GROUP BY action
ORDER BY logins DESC
`

type LoginsByProviderSinceRow struct {
	Action string
	Logins int64
	Users  int64
}

// Sign-in events by RU provider (406-FZ: yandex / vk / email-OTP).
func (q *Queries) LoginsByProviderSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]LoginsByProviderSinceRow, error) {
	rows, err := q.db.Query(ctx, loginsByProviderSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoginsByProviderSinceRow
	for rows.Next() {
		var i LoginsByProviderSinceRow
		if err := rows.Scan(&i.Action, &i.Logins, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageStatusByDay = `-- name: MessageStatusByDay :many
SELECT
    date_trunc('day', created_at, 'UTC')::timestamptz    AS day,
    COUNT(*) FILTER (WHERE status = 'complete')::bigint  AS complete,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint    AS failed,
    COUNT(*) FILTER (WHERE status = 'cancelled')::bigint AS cancelled
FROM messages
WHERE role = 'assistant' AND created_at >= $1
GROUP BY 1
ORDER BY 1
`

type MessageStatusByDayRow struct {
	Day       pgtype.Timestamptz
	Complete  int64
	Failed    int64
	Cancelled int64
}

func (q *Queries) MessageStatusByDay(ctx context.Context, createdAt pgtype.Timestamptz) ([]MessageStatusByDayRow, error) {
	rows, err := q.db.Query(ctx, messageStatusByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageStatusByDayRow
	for rows.Next() {
		var i MessageStatusByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Complete,
			&i.Failed,
			&i.Cancelled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageStatusCountsSince = `-- name: MessageStatusCountsSince :one
SELECT
    COUNT(*) FILTER (WHERE status = 'complete')::bigint  AS complete,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint    AS failed,
    COUNT(*) FILTER (WHERE status = 'cancelled')::bigint AS cancelled,
    COUNT(*) FILTER (WHERE status = 'pending')::bigint   AS pending
FROM messages
WHERE role = 'assistant' AND created_at >= $1
`

type MessageStatusCountsSinceRow struct {
	Complete  int64
	Failed    int64
	Cancelled int64
	Pending   int64
}

// Terminal-status breakdown of assistant turns; success_rate = complete / (complete+failed+cancelled).
func (q *Queries) MessageStatusCountsSince(ctx context.Context, createdAt pgtype.Timestamptz) (MessageStatusCountsSinceRow, error) {
	row := q.db.QueryRow(ctx, messageStatusCountsSince, createdAt)
	var i MessageStatusCountsSinceRow
	err := row.Scan(
		&i.Complete,
		&i.Failed,
		&i.Cancelled,
		&i.Pending,
	)
	return i, err
}

const messagesByDay = `-- name: MessagesByDay :many
SELECT date_trunc('day', created_at, 'UTC')::timestamptz AS day, COUNT(*) AS count
FROM messages
WHERE role = 'user' AND created_at >= $1
GROUP BY 1
ORDER BY 1
`

type MessagesByDayRow struct {
	Day   pgtype.Timestamptz
	Count int64
}

func (q *Queries) MessagesByDay(ctx context.Context, createdAt pgtype.Timestamptz) ([]MessagesByDayRow, error) {
	rows, err := q.db.Query(ctx, messagesByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesByDayRow
	for rows.Next() {
		var i MessagesByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const otpStatsSince = `-- name: OtpStatsSince :one
SELECT
    COUNT(*)::bigint                                                       AS issued,
    COUNT(*) FILTER (WHERE used_at IS NOT NULL)::bigint                    AS used,
    COUNT(*) FILTER (WHERE attempts >= 5)::bigint                          AS exhausted,
    COUNT(*) FILTER (WHERE used_at IS NULL AND expires_at < NOW())::bigint AS expired_unused
FROM email_codes
WHERE created_at >= $1
`

type OtpStatsSinceRow struct {
	Issued        int64
	Used          int64
	Exhausted     int64
	ExpiredUnused int64
}

// email-OTP delivery + abuse. delivery_rate = used/issued (silent SMTP failure
// shows as a drop); exhausted = codes that hit the attempt cap (brute force).
func (q *Queries) OtpStatsSince(ctx context.Context, createdAt pgtype.Timestamptz) (OtpStatsSinceRow, error) {
	row := q.db.QueryRow(ctx, otpStatsSince, createdAt)
	var i OtpStatsSinceRow
	err := row.Scan(
		&i.Issued,
		&i.Used,
		&i.Exhausted,
		&i.ExpiredUnused,
	)
	return i, err
}

const photoVoiceFunnelSince = `-- name: PhotoVoiceFunnelSince :one

WITH seq AS (
    SELECT
        m.id, m.role,
        EXISTS (SELECT 1 FROM message_blocks b WHERE b.message_id = m.id AND b.type = 'image') AS has_image,
        EXISTS (SELECT 1 FROM message_blocks b WHERE b.message_id = m.id AND b.type = 'audio') AS has_audio,
        LEAD(m.role)   OVER w AS next_role,
        LEAD(m.status) OVER w AS next_status
    FROM messages m
    WHERE m.created_at >= $1 AND m.role IN ('user', 'assistant')
    WINDOW w AS (PARTITION BY m.conversation_id ORDER BY m.created_at)
)
SELECT
    COUNT(*) FILTER (WHERE role = 'user')::bigint                                    AS total,
    COUNT(*) FILTER (WHERE role = 'user' AND has_image)::bigint                      AS photo,
    COUNT(*) FILTER (WHERE role = 'user' AND has_audio)::bigint                      AS voice,
    COUNT(*) FILTER (WHERE role = 'user' AND has_image AND next_role = 'assistant')::bigint                          AS photo_answered,
    COUNT(*) FILTER (WHERE role = 'user' AND has_image AND next_role = 'assistant' AND next_status = 'complete')::bigint AS photo_ok,
    COUNT(*) FILTER (WHERE role = 'user' AND has_audio AND next_role = 'assistant')::bigint                          AS voice_answered,
    COUNT(*) FILTER (WHERE role = 'user' AND has_audio AND next_role = 'assistant' AND next_status = 'complete')::bigint AS voice_ok
FROM seq
`

type PhotoVoiceFunnelSinceRow struct {
	Total         int64
	Photo         int64
	Voice         int64
	PhotoAnswered int64
	PhotoOk       int64
	VoiceAnswered int64
	VoiceOk       int64
}

// ============================================================================
// Photo & voice funnel (product core). The assistant reply is the next message
// after the user message in the same conversation (LEAD over created_at).
// ============================================================================
func (q *Queries) PhotoVoiceFunnelSince(ctx context.Context, createdAt pgtype.Timestamptz) (PhotoVoiceFunnelSinceRow, error) {
	row := q.db.QueryRow(ctx, photoVoiceFunnelSince, createdAt)
	var i PhotoVoiceFunnelSinceRow
	err := row.Scan(
		&i.Total,
		&i.Photo,
		&i.Voice,
		&i.PhotoAnswered,
		&i.PhotoOk,
		&i.VoiceAnswered,
		&i.VoiceOk,
	)
	return i, err
}

const problemDistributionSince = `-- name: ProblemDistributionSince :many

SELECT
    problem,
    COUNT(*)::bigint                            AS total,
    COUNT(*) FILTER (WHERE NOT matched)::bigint AS misses
FROM diag_events
WHERE created_at >= $1
GROUP BY problem
ORDER BY total DESC
`

type ProblemDistributionSinceRow struct {
	Problem string
	Total   int64
	Misses  int64
}

// ============================================================================
// Catalog & assortment.
// ============================================================================
// How often each diagnosed problem is queried and how often the catalog had no
// match (assortment gap). problem is a closed enum (non-PII).
func (q *Queries) ProblemDistributionSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]ProblemDistributionSinceRow, error) {
	rows, err := q.db.Query(ctx, problemDistributionSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProblemDistributionSinceRow
	for rows.Next() {
		var i ProblemDistributionSinceRow
		if err := rows.Scan(&i.Problem, &i.Total, &i.Misses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const responseLengthByVerdictSince = `-- name: ResponseLengthByVerdictSince :one
SELECT
    COALESCE(AVG(m.tokens_out) FILTER (WHERE f.value = 'up'), 0)::float8   AS avg_up,
    COALESCE(AVG(m.tokens_out) FILTER (WHERE f.value = 'down'), 0)::float8 AS avg_down,
    COALESCE(AVG(m.tokens_out) FILTER (WHERE f.value IS NULL), 0)::float8  AS avg_none,
    COUNT(*) FILTER (WHERE f.value = 'up')::bigint   AS n_up,
    COUNT(*) FILTER (WHERE f.value = 'down')::bigint AS n_down,
    COUNT(*) FILTER (WHERE f.value IS NULL)::bigint  AS n_none
FROM messages m
LEFT JOIN message_feedback f ON f.message_id = m.id
WHERE m.role = 'assistant' AND m.status = 'complete' AND m.created_at >= $1
`

type ResponseLengthByVerdictSinceRow struct {
	AvgUp   float64
	AvgDown float64
	AvgNone float64
	NUp     int64
	NDown   int64
	NNone   int64
}

// Average answer length (tokens_out) split by feedback verdict; the question is
// whether disliked answers are systematically longer or shorter.
func (q *Queries) ResponseLengthByVerdictSince(ctx context.Context, createdAt pgtype.Timestamptz) (ResponseLengthByVerdictSinceRow, error) {
	row := q.db.QueryRow(ctx, responseLengthByVerdictSince, createdAt)
	var i ResponseLengthByVerdictSinceRow
	err := row.Scan(
		&i.AvgUp,
		&i.AvgDown,
		&i.AvgNone,
		&i.NUp,
		&i.NDown,
		&i.NNone,
	)
	return i, err
}

const retentionBacklog = `-- name: RetentionBacklog :one
SELECT
    (SELECT COUNT(*) FROM email_codes WHERE expires_at < NOW())::bigint  AS expired_otp,
    (SELECT COUNT(*) FROM oauth_states WHERE expires_at < NOW())::bigint AS expired_oauth,
    (SELECT COUNT(*) FROM refresh_tokens WHERE revoked_at IS NOT NULL AND revoked_at < $1)::bigint AS old_revoked
`

type RetentionBacklogRow struct {
	ExpiredOtp   int64
	ExpiredOauth int64
	OldRevoked   int64
}

// Service-table rows past their useful life (data-minimisation check, 152-FZ).
func (q *Queries) RetentionBacklog(ctx context.Context, revokedBefore pgtype.Timestamptz) (RetentionBacklogRow, error) {
	row := q.db.QueryRow(ctx, retentionBacklog, revokedBefore)
	var i RetentionBacklogRow
	err := row.Scan(&i.ExpiredOtp, &i.ExpiredOauth, &i.OldRevoked)
	return i, err
}

const retentionCohorts = `-- name: RetentionCohorts :many
WITH cohort AS (
    SELECT u.id, u.created_at
    FROM users u
    WHERE u.deleted_at IS NULL AND u.created_at >= $1
),
flags AS (
    SELECT
        date_trunc('week', c.created_at, 'UTC') AS week,
        (NOW() >= c.created_at + interval '2 day')  AS elig_d1,
        (NOW() >= c.created_at + interval '8 day')  AS elig_d7,
        (NOW() >= c.created_at + interval '31 day') AS elig_d30,
        EXISTS (SELECT 1 FROM messages m WHERE m.user_id = c.id AND m.role = 'user'
            AND m.created_at >= c.created_at + interval '1 day'
            AND m.created_at <  c.created_at + interval '2 day') AS ret_d1,
        EXISTS (SELECT 1 FROM messages m WHERE m.user_id = c.id AND m.role = 'user'
            AND m.created_at >= c.created_at + interval '7 day'
            AND m.created_at <  c.created_at + interval '8 day') AS ret_d7,
        EXISTS (SELECT 1 FROM messages m WHERE m.user_id = c.id AND m.role = 'user'
            AND m.created_at >= c.created_at + interval '30 day'
            AND m.created_at <  c.created_at + interval '31 day') AS ret_d30
    FROM cohort c
)
SELECT
    week::timestamptz                                         AS week,
    COUNT(*)::bigint                                          AS size,
    COUNT(*) FILTER (WHERE elig_d1)::bigint                   AS d1_eligible,
    COUNT(*) FILTER (WHERE elig_d1 AND ret_d1)::bigint        AS d1_retained,
    COUNT(*) FILTER (WHERE elig_d7)::bigint                   AS d7_eligible,
    COUNT(*) FILTER (WHERE elig_d7 AND ret_d7)::bigint        AS d7_retained,
    COUNT(*) FILTER (WHERE elig_d30)::bigint                  AS d30_eligible,
    COUNT(*) FILTER (WHERE elig_d30 AND ret_d30)::bigint      AS d30_retained
FROM flags
GROUP BY week
ORDER BY week
`

type RetentionCohortsRow struct {
	Week        pgtype.Timestamptz
	Size        int64
	D1Eligible  int64
	D1Retained  int64
	D7Eligible  int64
	D7Retained  int64
	D30Eligible int64
	D30Retained int64
}

// Weekly sign-up cohorts with D1/D7/D30 return rates. Eligibility gates the
// denominator so a young cohort that has not yet reached day N is not counted as
// "churned" (retained / eligible, not retained / size). Computed live; move to a
// materialized view if message volume grows.
func (q *Queries) RetentionCohorts(ctx context.Context, createdAt pgtype.Timestamptz) ([]RetentionCohortsRow, error) {
	rows, err := q.db.Query(ctx, retentionCohorts, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetentionCohortsRow
	for rows.Next() {
		var i RetentionCohortsRow
		if err := rows.Scan(
			&i.Week,
			&i.Size,
			&i.D1Eligible,
			&i.D1Retained,
			&i.D7Eligible,
			&i.D7Retained,
			&i.D30Eligible,
			&i.D30Retained,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCostBetween = `-- name: SumCostBetween :one
SELECT COALESCE(SUM(cost_usd), 0)::numeric AS cost_usd
FROM usage_log
WHERE created_at >= $1 AND created_at < $2 AND endpoint NOT LIKE 'fertilizer_tap:%'
`

type SumCostBetweenParams struct {
	FromTs pgtype.Timestamptz
	ToTs   pgtype.Timestamptz
}

// Bounded-window Claude spend for month-to-date vs previous-month comparison.
func (q *Queries) SumCostBetween(ctx context.Context, arg SumCostBetweenParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumCostBetween, arg.FromTs, arg.ToTs)
	var cost_usd pgtype.Numeric
	err := row.Scan(&cost_usd)
	return cost_usd, err
}

const sumUsageSince = `-- name: SumUsageSince :one
SELECT
    COALESCE(SUM(tokens_in), 0)::bigint    AS tokens_in,
    COALESCE(SUM(tokens_out), 0)::bigint   AS tokens_out,
    COALESCE(SUM(cost_usd), 0)::numeric    AS cost_usd
FROM usage_log
WHERE created_at >= $1 AND endpoint NOT LIKE 'fertilizer_tap:%'
`

type SumUsageSinceRow struct {
	TokensIn  int64
	TokensOut int64
	CostUsd   pgtype.Numeric
}

func (q *Queries) SumUsageSince(ctx context.Context, createdAt pgtype.Timestamptz) (SumUsageSinceRow, error) {
	row := q.db.QueryRow(ctx, sumUsageSince, createdAt)
	var i SumUsageSinceRow
	err := row.Scan(&i.TokensIn, &i.TokensOut, &i.CostUsd)
	return i, err
}

const suspiciousIPsSince = `-- name: SuspiciousIPsSince :many
WITH cutoff AS (SELECT $1::timestamptz AS ts)
SELECT source, ip, COUNT(*)::bigint AS count
FROM (
    SELECT 'admin_login_failed'::text AS source, admin_audit_log.ip
        FROM admin_audit_log, cutoff
        WHERE admin_audit_log.action = 'admin_login_failed'
          AND admin_audit_log.ip IS NOT NULL
          AND admin_audit_log.created_at >= cutoff.ts
    UNION ALL
    SELECT 'refresh_reuse'::text AS source, audit_log.ip
        FROM audit_log, cutoff
        WHERE audit_log.action = 'refresh_reuse_detected'
          AND audit_log.ip IS NOT NULL
          AND audit_log.created_at >= cutoff.ts
) t
GROUP BY source, ip
ORDER BY count DESC
LIMIT 20
`

type SuspiciousIPsSinceRow struct {
	Source string
	Ip     *netip.Addr
	Count  int64
}

// IPs by failed-auth volume: admin-panel brute force + refresh-token reuse. The
// cutoff is an explicitly-typed CTE so sqlc resolves the param across the UNION.
func (q *Queries) SuspiciousIPsSince(ctx context.Context, since pgtype.Timestamptz) ([]SuspiciousIPsSinceRow, error) {
	rows, err := q.db.Query(ctx, suspiciousIPsSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuspiciousIPsSinceRow
	for rows.Next() {
		var i SuspiciousIPsSinceRow
		if err := rows.Scan(&i.Source, &i.Ip, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tapsBySlugSince = `-- name: TapsBySlugSince :many
SELECT split_part(endpoint, ':', 2) AS slug, COUNT(*)::bigint AS taps
FROM usage_log
WHERE endpoint LIKE 'fertilizer_tap:%' AND created_at >= $1
GROUP BY 1
`

type TapsBySlugSinceRow struct {
	Slug string
	Taps int64
}

// All slugs (unbounded, unlike TopFertilizerTaps) so CTR can be joined per slug.
func (q *Queries) TapsBySlugSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]TapsBySlugSinceRow, error) {
	rows, err := q.db.Query(ctx, tapsBySlugSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TapsBySlugSinceRow
	for rows.Next() {
		var i TapsBySlugSinceRow
		if err := rows.Scan(&i.Slug, &i.Taps); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topCostUsersSince = `-- name: TopCostUsersSince :many
SELECT
    user_id,
    COUNT(*)::bigint                       AS requests,
    COALESCE(SUM(tokens_in), 0)::bigint    AS tokens_in,
    COALESCE(SUM(tokens_out), 0)::bigint   AS tokens_out,
    COALESCE(SUM(cost_usd), 0)::numeric    AS cost_usd
FROM usage_log
WHERE created_at >= $1 AND endpoint NOT LIKE 'fertilizer_tap:%' AND endpoint <> 'transcribe'
GROUP BY user_id
ORDER BY cost_usd DESC
LIMIT 20
`

type TopCostUsersSinceRow struct {
	UserID    uuid.UUID
	Requests  int64
	TokensIn  int64
	TokensOut int64
	CostUsd   pgtype.Numeric
}

// Most expensive users by Claude spend (taps excluded). user_id is masked to a hex
// prefix in the usecase before it leaves the backend (CLAUDE.md invariant #3/#10).
func (q *Queries) TopCostUsersSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]TopCostUsersSinceRow, error) {
	rows, err := q.db.Query(ctx, topCostUsersSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopCostUsersSinceRow
	for rows.Next() {
		var i TopCostUsersSinceRow
		if err := rows.Scan(
			&i.UserID,
			&i.Requests,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topFertilizerTaps = `-- name: TopFertilizerTaps :many
SELECT split_part(endpoint, ':', 2) AS slug, COUNT(*) AS taps
FROM usage_log
WHERE endpoint LIKE 'fertilizer_tap:%' AND created_at >= $1
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
`

type TopFertilizerTapsRow struct {
	Slug string
	Taps int64
}

func (q *Queries) TopFertilizerTaps(ctx context.Context, createdAt pgtype.Timestamptz) ([]TopFertilizerTapsRow, error) {
	rows, err := q.db.Query(ctx, topFertilizerTaps, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopFertilizerTapsRow
	for rows.Next() {
		var i TopFertilizerTapsRow
		if err := rows.Scan(&i.Slug, &i.Taps); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topOtpRequestersSince = `-- name: TopOtpRequestersSince :many
SELECT email, COUNT(*)::bigint AS codes
FROM email_codes
WHERE created_at >= $1
GROUP BY email
HAVING COUNT(*) >= $2
ORDER BY codes DESC
LIMIT 20
`

type TopOtpRequestersSinceParams struct {
	Since    pgtype.Timestamptz
	MinCodes interface{}
}

type TopOtpRequestersSinceRow struct {
	Email string
	Codes int64
}

// Emails requesting the most codes (mailbox-flood / enumeration). email is
// masked in the usecase before it leaves the backend.
func (q *Queries) TopOtpRequestersSince(ctx context.Context, arg TopOtpRequestersSinceParams) ([]TopOtpRequestersSinceRow, error) {
	rows, err := q.db.Query(ctx, topOtpRequestersSince, arg.Since, arg.MinCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopOtpRequestersSinceRow
	for rows.Next() {
		var i TopOtpRequestersSinceRow
		if err := rows.Scan(&i.Email, &i.Codes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transcriptionVolumeSince = `-- name: TranscriptionVolumeSince :one
SELECT COUNT(*)::bigint AS count, COALESCE(SUM(duration_ms), 0)::bigint AS total_ms
FROM usage_log
WHERE endpoint = 'transcribe' AND created_at >= $1
`

type TranscriptionVolumeSinceRow struct {
	Count   int64
	TotalMs int64
}

// SpeechKit transcription volume (post-0017 rows carry duration_ms).
func (q *Queries) TranscriptionVolumeSince(ctx context.Context, createdAt pgtype.Timestamptz) (TranscriptionVolumeSinceRow, error) {
	row := q.db.QueryRow(ctx, transcriptionVolumeSince, createdAt)
	var i TranscriptionVolumeSinceRow
	err := row.Scan(&i.Count, &i.TotalMs)
	return i, err
}

const unitEconomicsSince = `-- name: UnitEconomicsSince :one

SELECT
    COALESCE(SUM(cost_usd), 0)::numeric                                      AS cost_usd,
    COALESCE(SUM(tokens_in), 0)::bigint                                      AS tokens_in,
    COALESCE(SUM(tokens_out), 0)::bigint                                     AS tokens_out,
    COUNT(*) FILTER (WHERE endpoint = '/v1/messages')::bigint                AS messages,
    COUNT(DISTINCT user_id) FILTER (WHERE endpoint = '/v1/messages')::bigint AS users
FROM usage_log
WHERE created_at >= $1 AND endpoint NOT LIKE 'fertilizer_tap:%' AND endpoint <> 'transcribe'
`

type UnitEconomicsSinceRow struct {
	CostUsd   pgtype.Numeric
	TokensIn  int64
	TokensOut int64
	Messages  int64
	Users     int64
}

// ============================================================================
// Cost / FinOps. Claude rows are endpoint='/v1/messages'; taps and 'transcribe'
// carry no Claude cost (cost_usd NULL → ignored by the SUMs).
// ============================================================================
func (q *Queries) UnitEconomicsSince(ctx context.Context, createdAt pgtype.Timestamptz) (UnitEconomicsSinceRow, error) {
	row := q.db.QueryRow(ctx, unitEconomicsSince, createdAt)
	var i UnitEconomicsSinceRow
	err := row.Scan(
		&i.CostUsd,
		&i.TokensIn,
		&i.TokensOut,
		&i.Messages,
		&i.Users,
	)
	return i, err
}

const uploadGCStatsBefore = `-- name: UploadGCStatsBefore :one
SELECT
    COUNT(*) FILTER (WHERE used = FALSE)::bigint                                         AS unused_total,
    COUNT(*) FILTER (WHERE used = FALSE AND created_at < $1)::bigint                     AS stale_total,
    COALESCE(SUM(size_bytes) FILTER (WHERE used = FALSE AND created_at < $1), 0)::bigint AS stale_bytes
FROM uploads
`

type UploadGCStatsBeforeRow struct {
	UnusedTotal int64
	StaleTotal  int64
	StaleBytes  int64
}

// Orphaned uploads: presigned-but-never-attached, and the stale subset (older
// than the GC window) that the cron should have removed.
func (q *Queries) UploadGCStatsBefore(ctx context.Context, createdAt pgtype.Timestamptz) (UploadGCStatsBeforeRow, error) {
	row := q.db.QueryRow(ctx, uploadGCStatsBefore, createdAt)
	var i UploadGCStatsBeforeRow
	err := row.Scan(&i.UnusedTotal, &i.StaleTotal, &i.StaleBytes)
	return i, err
}

const usageByDay = `-- name: UsageByDay :many
SELECT
    date_trunc('day', created_at, 'UTC')::timestamptz AS day,
    COALESCE(SUM(tokens_in), 0)::bigint             AS tokens_in,
    COALESCE(SUM(tokens_out), 0)::bigint            AS tokens_out,
    COALESCE(SUM(cost_usd), 0)::numeric             AS cost_usd
FROM usage_log
WHERE created_at >= $1 AND endpoint NOT LIKE 'fertilizer_tap:%'
GROUP BY 1
ORDER BY 1
`

type UsageByDayRow struct {
	Day       pgtype.Timestamptz
	TokensIn  int64
	TokensOut int64
	CostUsd   pgtype.Numeric
}

func (q *Queries) UsageByDay(ctx context.Context, createdAt pgtype.Timestamptz) ([]UsageByDayRow, error) {
	rows, err := q.db.Query(ctx, usageByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageByDayRow
	for rows.Next() {
		var i UsageByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageResidueDeletedUsers = `-- name: UsageResidueDeletedUsers :one
SELECT
    COUNT(*)::bigint                   AS rows,
    COUNT(DISTINCT ul.user_id)::bigint AS users,
    MIN(ul.created_at)::timestamptz    AS oldest
FROM usage_log ul
JOIN users u ON u.id = ul.user_id
WHERE u.deleted_at IS NOT NULL
`

type UsageResidueDeletedUsersRow struct {
	Rows   int64
	Users  int64
	Oldest pgtype.Timestamptz
}

// usage_log is the one table not cascaded on account deletion (kept for billing);
// this surfaces how much is still tied to deleted users and how old it is.
func (q *Queries) UsageResidueDeletedUsers(ctx context.Context) (UsageResidueDeletedUsersRow, error) {
	row := q.db.QueryRow(ctx, usageResidueDeletedUsers)
	var i UsageResidueDeletedUsersRow
	err := row.Scan(&i.Rows, &i.Users, &i.Oldest)
	return i, err
}

const usersByDay = `-- name: UsersByDay :many
SELECT date_trunc('day', created_at, 'UTC')::timestamptz AS day, COUNT(*) AS count
FROM users
WHERE created_at >= $1
GROUP BY 1
ORDER BY 1
`

type UsersByDayRow struct {
	Day   pgtype.Timestamptz
	Count int64
}

func (q *Queries) UsersByDay(ctx context.Context, createdAt pgtype.Timestamptz) ([]UsersByDayRow, error) {
	rows, err := q.db.Query(ctx, usersByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersByDayRow
	for rows.Next() {
		var i UsersByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
