// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one

SELECT COUNT(*) FROM admin_users
`

// Admin panel queries: operator account, sessions, one-time codes, audit log
// and the server error feed.
func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countErrorEventsSince = `-- name: CountErrorEventsSince :one
SELECT COUNT(*) FROM admin_error_events WHERE created_at >= $1
`

func (q *Queries) CountErrorEventsSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countErrorEventsSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentAdminCodes = `-- name: CountRecentAdminCodes :one
SELECT COUNT(*) FROM admin_codes
WHERE email = $1 AND purpose = $2 AND created_at >= $3
`

type CountRecentAdminCodesParams struct {
	Email     string
	Purpose   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountRecentAdminCodes(ctx context.Context, arg CountRecentAdminCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentAdminCodes, arg.Email, arg.Purpose, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedAdminLogins = `-- name: CountRecentFailedAdminLogins :one
SELECT COUNT(*) FROM admin_audit_log
WHERE action = 'admin_login_failed' AND ip = $1 AND created_at >= $2
`

type CountRecentFailedAdminLoginsParams struct {
	Ip        *netip.Addr
	CreatedAt pgtype.Timestamptz
}

// DB-baseline brute-force guard: failed logins from one IP inside the window.
func (q *Queries) CountRecentFailedAdminLogins(ctx context.Context, arg CountRecentFailedAdminLoginsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedAdminLogins, arg.Ip, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedAdminLoginsGlobal = `-- name: CountRecentFailedAdminLoginsGlobal :one
SELECT COUNT(*) FROM admin_audit_log
WHERE action = 'admin_login_failed' AND created_at >= $1
`

// Account-global guard (IP-independent): closes the per-IP bypass when an
// attacker rotates spoofed X-Forwarded-For values. The single-operator panel
// has one account, so a global cap is acceptable; it self-heals after the window.
func (q *Queries) CountRecentFailedAdminLoginsGlobal(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedAdminLoginsGlobal, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at, updated_at, last_login_at
`

type CreateAdminParams struct {
	Email        string
	PasswordHash []byte
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.PasswordHash)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createAdminCode = `-- name: CreateAdminCode :one
INSERT INTO admin_codes (email, purpose, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, purpose, code_hash, attempts, expires_at, used_at, created_at
`

type CreateAdminCodeParams struct {
	Email     string
	Purpose   string
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAdminCode(ctx context.Context, arg CreateAdminCodeParams) (AdminCode, error) {
	row := q.db.QueryRow(ctx, createAdminCode,
		arg.Email,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i AdminCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin_sessions (admin_id, token_hash, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, admin_id, token_hash, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at
`

type CreateAdminSessionParams struct {
	AdminID   uuid.UUID
	TokenHash []byte
	Ip        *netip.Addr
	UserAgent pgtype.Text
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.AdminID,
		arg.TokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredAdminCodes = `-- name: DeleteExpiredAdminCodes :execrows
DELETE FROM admin_codes WHERE expires_at < NOW() - INTERVAL '1 day'
`

func (q *Queries) DeleteExpiredAdminCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAdminCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :execrows
DELETE FROM admin_sessions WHERE expires_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAdminSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldErrorEvents = `-- name: DeleteOldErrorEvents :execrows
DELETE FROM admin_error_events WHERE created_at < $1
`

func (q *Queries) DeleteOldErrorEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldErrorEvents, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAdminCode = `-- name: GetActiveAdminCode :one
SELECT id, email, purpose, code_hash, attempts, expires_at, used_at, created_at FROM admin_codes
WHERE email = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveAdminCodeParams struct {
	Email   string
	Purpose string
}

func (q *Queries) GetActiveAdminCode(ctx context.Context, arg GetActiveAdminCodeParams) (AdminCode, error) {
	row := q.db.QueryRow(ctx, getActiveAdminCode, arg.Email, arg.Purpose)
	var i AdminCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, created_at, updated_at, last_login_at FROM admin_users WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, created_at, updated_at, last_login_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminSessionByHash = `-- name: GetAdminSessionByHash :one
SELECT id, admin_id, token_hash, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM admin_sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetAdminSessionByHash(ctx context.Context, tokenHash []byte) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSessionByHash, tokenHash)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const incrementAdminCodeAttempts = `-- name: IncrementAdminCodeAttempts :one
UPDATE admin_codes SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) IncrementAdminCodeAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementAdminCodeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const insertAdminAudit = `-- name: InsertAdminAudit :exec
INSERT INTO admin_audit_log (admin_id, action, entity, entity_id, details, ip)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAdminAuditParams struct {
	AdminID  pgtype.UUID
	Action   string
	Entity   pgtype.Text
	EntityID pgtype.Text
	Details  []byte
	Ip       *netip.Addr
}

func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error {
	_, err := q.db.Exec(ctx, insertAdminAudit,
		arg.AdminID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Details,
		arg.Ip,
	)
	return err
}

const insertErrorEvent = `-- name: InsertErrorEvent :exec
INSERT INTO admin_error_events (source, route, method, status, request_id, message)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertErrorEventParams struct {
	Source    string
	Route     string
	Method    string
	Status    int32
	RequestID pgtype.Text
	Message   pgtype.Text
}

func (q *Queries) InsertErrorEvent(ctx context.Context, arg InsertErrorEventParams) error {
	_, err := q.db.Exec(ctx, insertErrorEvent,
		arg.Source,
		arg.Route,
		arg.Method,
		arg.Status,
		arg.RequestID,
		arg.Message,
	)
	return err
}

const listActiveAdminSessions = `-- name: ListActiveAdminSessions :many
SELECT id, admin_id, token_hash, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM admin_sessions
WHERE admin_id = $1 AND revoked_at IS NULL AND expires_at > NOW()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListActiveAdminSessions(ctx context.Context, adminID uuid.UUID) ([]AdminSession, error) {
	rows, err := q.db.Query(ctx, listActiveAdminSessions, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSession
	for rows.Next() {
		var i AdminSession
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.TokenHash,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminAudit = `-- name: ListAdminAudit :many
SELECT id, admin_id, action, entity, entity_id, details, ip, created_at FROM admin_audit_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminAuditParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAdminAudit(ctx context.Context, arg ListAdminAuditParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLog
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Details,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorEvents = `-- name: ListErrorEvents :many
SELECT id, source, route, method, status, request_id, message, created_at FROM admin_error_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListErrorEventsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListErrorEvents(ctx context.Context, arg ListErrorEventsParams) ([]AdminErrorEvent, error) {
	rows, err := q.db.Query(ctx, listErrorEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminErrorEvent
	for rows.Next() {
		var i AdminErrorEvent
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Route,
			&i.Method,
			&i.Status,
			&i.RequestID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAdminCodeUsed = `-- name: MarkAdminCodeUsed :exec
UPDATE admin_codes SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkAdminCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAdminCodeUsed, id)
	return err
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeAdminSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, id)
	return err
}

const revokeAllAdminSessions = `-- name: RevokeAllAdminSessions :exec
UPDATE admin_sessions
SET revoked_at = NOW()
WHERE admin_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAdminSessions(ctx context.Context, adminID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAdminSessions, adminID)
	return err
}

const revokeOtherAdminSessions = `-- name: RevokeOtherAdminSessions :exec
UPDATE admin_sessions
SET revoked_at = NOW()
WHERE admin_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherAdminSessionsParams struct {
	AdminID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) RevokeOtherAdminSessions(ctx context.Context, arg RevokeOtherAdminSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherAdminSessions, arg.AdminID, arg.ID)
	return err
}

const touchAdminLogin = `-- name: TouchAdminLogin :exec
UPDATE admin_users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) TouchAdminLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAdminLogin, id)
	return err
}

const touchAdminSession = `-- name: TouchAdminSession :exec
UPDATE admin_sessions
SET last_seen_at = NOW(), expires_at = $2
WHERE id = $1
`

type TouchAdminSessionParams struct {
	ID        uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

// Sliding TTL: bump both the activity stamp and the expiry on use.
func (q *Queries) TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) error {
	_, err := q.db.Exec(ctx, touchAdminSession, arg.ID, arg.ExpiresAt)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           uuid.UUID
	PasswordHash []byte
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}
