// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (user_id, action, details, ip)
VALUES ($1, $2, $3, $4)
`

type InsertAuditLogParams struct {
	UserID  pgtype.UUID
	Action  string
	Details []byte
	Ip      *netip.Addr
}

// user_id is nullable for system-level events (e.g. failed verification of an
// id_token before any user could be resolved).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.Details,
		arg.Ip,
	)
	return err
}

const listAuditByUser = `-- name: ListAuditByUser :many
SELECT id, user_id, action, details, ip, created_at FROM audit_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListAuditByUser(ctx context.Context, arg ListAuditByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
