// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getConversationByUser = `-- name: GetConversationByUser :one
SELECT id, user_id, created_at FROM conversations WHERE user_id = $1
`

func (q *Queries) GetConversationByUser(ctx context.Context, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByUser, userID)
	var i Conversation
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getOrCreateConversation = `-- name: GetOrCreateConversation :one
INSERT INTO conversations (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = conversations.user_id
RETURNING id, user_id, created_at
`

// Idempotent: one chat per user. The DO UPDATE is a no-op that exists only so
// RETURNING yields the existing row on conflict — atomic, race-free.
func (q *Queries) GetOrCreateConversation(ctx context.Context, userID uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getOrCreateConversation, userID)
	var i Conversation
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}
