// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diag.sql

package db

import (
	"context"
)

const insertDiagEvent = `-- name: InsertDiagEvent :exec
INSERT INTO diag_events (problem, matched) VALUES ($1, $2)
`

type InsertDiagEventParams struct {
	Problem string
	Matched bool
}

// One row per recommend_fertilizer call: the problem key the model queried and
// whether the catalog matched. No PII (problem is a closed enum). Written
// best-effort from the tool callback (fertilizer.Service.Recommend).
func (q *Queries) InsertDiagEvent(ctx context.Context, arg InsertDiagEventParams) error {
	_, err := q.db.Exec(ctx, insertDiagEvent, arg.Problem, arg.Matched)
	return err
}
