// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_codes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentEmailCodes = `-- name: CountRecentEmailCodes :one
SELECT COUNT(*) FROM email_codes
WHERE email = $1 AND created_at > NOW() - INTERVAL '1 hour'
`

// DB-level baseline for the ≤3-requests/hour/email rate limit. Redis adds a
// faster check in front of this when it lands (stage 2.3).
func (q *Queries) CountRecentEmailCodes(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentEmailCodes, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailCode = `-- name: CreateEmailCode :one
INSERT INTO email_codes (email, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, code_hash, attempts, expires_at, used_at, created_at
`

type CreateEmailCodeParams struct {
	Email     string
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailCode(ctx context.Context, arg CreateEmailCodeParams) (EmailCode, error) {
	row := q.db.QueryRow(ctx, createEmailCode, arg.Email, arg.CodeHash, arg.ExpiresAt)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveEmailCode = `-- name: GetActiveEmailCode :one
SELECT id, email, code_hash, attempts, expires_at, used_at, created_at FROM email_codes
WHERE email = $1
  AND used_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

// Returns the most recent unused, unexpired code for the email. Older codes
// become irrelevant the moment a newer code is issued.
func (q *Queries) GetActiveEmailCode(ctx context.Context, email string) (EmailCode, error) {
	row := q.db.QueryRow(ctx, getActiveEmailCode, email)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementEmailCodeAttempts = `-- name: IncrementEmailCodeAttempts :one
UPDATE email_codes
SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

// RETURNING attempts lets the caller atomically enforce the ≤5 attempts cap.
func (q *Queries) IncrementEmailCodeAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementEmailCodeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const markEmailCodeUsed = `-- name: MarkEmailCodeUsed :exec
UPDATE email_codes SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkEmailCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailCodeUsed, id)
	return err
}
