// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeMessage = `-- name: CompleteMessage :exec
UPDATE messages SET status = 'complete', tokens_in = $2, tokens_out = $3 WHERE id = $1
`

type CompleteMessageParams struct {
	ID        uuid.UUID
	TokensIn  pgtype.Int4
	TokensOut pgtype.Int4
}

// Finalises an assistant message: status + token counts (from the worker's SSE
// `usage` event, ARCH §11.3).
func (q *Queries) CompleteMessage(ctx context.Context, arg CompleteMessageParams) error {
	_, err := q.db.Exec(ctx, completeMessage, arg.ID, arg.TokensIn, arg.TokensOut)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, user_id, role, status, tokens_in, tokens_out, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
	Role           string
	Status         string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :execrows
DELETE FROM messages WHERE id = $1 AND user_id = $2
`

type DeleteMessageParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// DELETE /v1/messages/:id — owner-scoped (user_id in WHERE). execrows lets the
// handler distinguish 404 (0 rows) from 204 (1 row). Blocks cascade.
func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, conversation_id, user_id, role, status, tokens_in, tokens_out, created_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, conversation_id, user_id, role, status, tokens_in, tokens_out, created_at FROM messages
WHERE conversation_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMessagesBeforeParams struct {
	ConversationID  uuid.UUID
	BeforeCreatedAt pgtype.Timestamptz
	BeforeID        uuid.UUID
	Limit           int32
}

// Keyset page strictly older than the cursor. The row-value comparison rides
// the (conversation_id, created_at, id) index and is stable across created_at
// ties. Explicit casts so sqlc types the id cursor as uuid, not timestamptz.
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore,
		arg.ConversationID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.TokensIn,
			&i.TokensOut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, conversation_id, user_id, role, status, tokens_in, tokens_out, created_at FROM messages
WHERE conversation_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListRecentMessagesParams struct {
	ConversationID uuid.UUID
	Limit          int32
}

// First page of history (latest-first). The next cursor is the (created_at, id)
// of the last returned row.
func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.TokensIn,
			&i.TokensOut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE messages SET status = $2 WHERE id = $1
`

type UpdateMessageStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.Exec(ctx, updateMessageStatus, arg.ID, arg.Status)
	return err
}
