// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_blocks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessageBlock = `-- name: CreateMessageBlock :one
INSERT INTO message_blocks (message_id, order_index, type, content_text, storage_key, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, message_id, order_index, type, content_text, storage_key, metadata, created_at
`

type CreateMessageBlockParams struct {
	MessageID   uuid.UUID
	OrderIndex  int32
	Type        string
	ContentText pgtype.Text
	StorageKey  pgtype.Text
	Metadata    []byte
}

func (q *Queries) CreateMessageBlock(ctx context.Context, arg CreateMessageBlockParams) (MessageBlock, error) {
	row := q.db.QueryRow(ctx, createMessageBlock,
		arg.MessageID,
		arg.OrderIndex,
		arg.Type,
		arg.ContentText,
		arg.StorageKey,
		arg.Metadata,
	)
	var i MessageBlock
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.OrderIndex,
		&i.Type,
		&i.ContentText,
		&i.StorageKey,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listBlocksByMessageIDs = `-- name: ListBlocksByMessageIDs :many
SELECT id, message_id, order_index, type, content_text, storage_key, metadata, created_at FROM message_blocks
WHERE message_id = ANY($1::uuid[])
ORDER BY message_id, order_index
`

// Batch-loads blocks for a page of messages (avoids N+1). Caller groups by
// message_id; rows arrive ordered within each message by order_index.
func (q *Queries) ListBlocksByMessageIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]MessageBlock, error) {
	rows, err := q.db.Query(ctx, listBlocksByMessageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageBlock
	for rows.Next() {
		var i MessageBlock
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.OrderIndex,
			&i.Type,
			&i.ContentText,
			&i.StorageKey,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
