// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_feedback.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteMessageFeedback = `-- name: DeleteMessageFeedback :exec
DELETE FROM message_feedback WHERE message_id = $1 AND user_id = $2
`

type DeleteMessageFeedbackParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
}

// Clears the caller's verdict on a message. Idempotent (no-op if absent).
func (q *Queries) DeleteMessageFeedback(ctx context.Context, arg DeleteMessageFeedbackParams) error {
	_, err := q.db.Exec(ctx, deleteMessageFeedback, arg.MessageID, arg.UserID)
	return err
}

const upsertMessageFeedback = `-- name: UpsertMessageFeedback :exec
INSERT INTO message_feedback (message_id, user_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, user_id) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type UpsertMessageFeedbackParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Value     string
}

// PUT /v1/messages/:id/feedback — owner-scoped (user_id in the key). Idempotent:
// re-voting the same value just refreshes updated_at.
func (q *Queries) UpsertMessageFeedback(ctx context.Context, arg UpsertMessageFeedbackParams) error {
	_, err := q.db.Exec(ctx, upsertMessageFeedback, arg.MessageID, arg.UserID, arg.Value)
	return err
}
