// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64
	UserID    pgtype.UUID
	Action    string
	Details   []byte
	Ip        *netip.Addr
	CreatedAt pgtype.Timestamptz
}

type EmailCode struct {
	ID        uuid.UUID
	Email     string
	CodeHash  []byte
	Attempts  int32
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	DeviceID   pgtype.Text
	UserAgent  pgtype.Text
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	Email         pgtype.Text
	EmailVerified bool
	AppleSub      pgtype.Text
	GoogleSub     pgtype.Text
	DisplayName   pgtype.Text
	Locale        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}
