// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_states.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states
WHERE state_hash = $1 AND provider = $2 AND expires_at > NOW()
RETURNING state_hash, provider, code_verifier, ip, created_at, expires_at
`

type ConsumeOAuthStateParams struct {
	StateHash []byte
	Provider  string
}

// Single-use: the row is removed atomically on first presentation, so a
// replayed state (or one stolen from the redirect) fails the second time.
func (q *Queries) ConsumeOAuthState(ctx context.Context, arg ConsumeOAuthStateParams) (OauthState, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, arg.StateHash, arg.Provider)
	var i OauthState
	err := row.Scan(
		&i.StateHash,
		&i.Provider,
		&i.CodeVerifier,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countActiveOAuthStatesByIP = `-- name: CountActiveOAuthStatesByIP :one
SELECT COUNT(*) FROM oauth_states WHERE ip = $1 AND expires_at > NOW()
`

// Anti-flood cap for POST /auth/{provider}/start.
func (q *Queries) CountActiveOAuthStatesByIP(ctx context.Context, ip pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOAuthStatesByIP, ip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOAuthState = `-- name: CreateOAuthState :exec
INSERT INTO oauth_states (state_hash, provider, code_verifier, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOAuthStateParams struct {
	StateHash    []byte
	Provider     string
	CodeVerifier string
	Ip           pgtype.Text
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState,
		arg.StateHash,
		arg.Provider,
		arg.CodeVerifier,
		arg.Ip,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at <= NOW()
`

// Opportunistic sweep, called best-effort on each new attempt.
func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthStates)
	return err
}
