// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// DB-level baseline for the ≤3-requests/hour/email rate limit. Redis adds a
	// faster check in front of this when it lands (stage 2.3).
	CountRecentEmailCodes(ctx context.Context, email string) (int64, error)
	CreateEmailCode(ctx context.Context, arg CreateEmailCodeParams) (EmailCode, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Periodic cleanup job (wired in a later stage). Keeps recently expired rows
	// for a week to aid debugging reuse incidents.
	DeleteExpiredRefreshTokens(ctx context.Context) error
	// Returns the most recent unused, unexpired code for the email. Older codes
	// become irrelevant the moment a newer code is issued.
	GetActiveEmailCode(ctx context.Context, email string) (EmailCode, error)
	// Intentionally returns the row even when revoked or expired so the caller
	// can implement reuse-detection (presenting a revoked token revokes the
	// whole family).
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetUserByAppleSub(ctx context.Context, appleSub pgtype.Text) (User, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByGoogleSub(ctx context.Context, googleSub pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// RETURNING attempts lets the caller atomically enforce the ≤5 attempts cap.
	IncrementEmailCodeAttempts(ctx context.Context, id uuid.UUID) (int32, error)
	// user_id is nullable for system-level events (e.g. failed verification of an
	// id_token before any user could be resolved).
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	LinkAppleSub(ctx context.Context, arg LinkAppleSubParams) (User, error)
	LinkGoogleSub(ctx context.Context, arg LinkGoogleSubParams) (User, error)
	ListAuditByUser(ctx context.Context, arg ListAuditByUserParams) ([]AuditLog, error)
	MarkEmailCodeUsed(ctx context.Context, id uuid.UUID) error
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SetUserEmail(ctx context.Context, arg SetUserEmailParams) (User, error)
	// Null out unique identifiers so the user can re-register with the same
	// email or OAuth subject later. Apple/Google review explicitly requires
	// account deletion to free up identifiers.
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	TouchRefreshToken(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
