// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (user_id, storage_key, content_type, size_bytes)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, storage_key, content_type, size_bytes, used, created_at
`

type CreateUploadParams struct {
	UserID      uuid.UUID
	StorageKey  string
	ContentType string
	SizeBytes   int64
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.UserID,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM uploads WHERE storage_key = $1
`

// Removes one upload row after its object has been deleted from storage (GC).
func (q *Queries) DeleteUpload(ctx context.Context, storageKey string) error {
	_, err := q.db.Exec(ctx, deleteUpload, storageKey)
	return err
}

const getUploadByStorageKey = `-- name: GetUploadByStorageKey :one
SELECT id, user_id, storage_key, content_type, size_bytes, used, created_at FROM uploads WHERE storage_key = $1
`

// Used by POST /v1/messages to verify the caller owns the referenced storage_key.
func (q *Queries) GetUploadByStorageKey(ctx context.Context, storageKey string) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadByStorageKey, storageKey)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const listUnusedUploadsBefore = `-- name: ListUnusedUploadsBefore :many
SELECT id, user_id, storage_key, content_type, size_bytes, used, created_at FROM uploads WHERE used = FALSE AND created_at < $1
`

// GC candidates: presigned-but-never-attached uploads older than the cutoff.
func (q *Queries) ListUnusedUploadsBefore(ctx context.Context, createdAt pgtype.Timestamptz) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listUnusedUploadsBefore, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upload
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Used,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUploadUsed = `-- name: MarkUploadUsed :exec
UPDATE uploads SET used = TRUE WHERE storage_key = $1
`

func (q *Queries) MarkUploadUsed(ctx context.Context, storageKey string) error {
	_, err := q.db.Exec(ctx, markUploadUsed, storageKey)
	return err
}
