// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_log.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertUsage = `-- name: InsertUsage :exec
INSERT INTO usage_log (user_id, endpoint, tokens_in, tokens_out, cost_usd)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUsageParams struct {
	UserID    uuid.UUID
	Endpoint  string
	TokensIn  pgtype.Int4
	TokensOut pgtype.Int4
	CostUsd   pgtype.Numeric
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) error {
	_, err := q.db.Exec(ctx, insertUsage,
		arg.UserID,
		arg.Endpoint,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostUsd,
	)
	return err
}

const sumUserTokensSince = `-- name: SumUserTokensSince :one
SELECT
    COALESCE(SUM(tokens_in), 0)::bigint AS tokens_in,
    COALESCE(SUM(tokens_out), 0)::bigint AS tokens_out
FROM usage_log
WHERE user_id = $1 AND created_at >= $2
`

type SumUserTokensSinceParams struct {
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type SumUserTokensSinceRow struct {
	TokensIn  int64
	TokensOut int64
}

// Backs per-user daily token limits and budget alerts (ARCH §13 cost risk; wired
// in Stage 2.3).
func (q *Queries) SumUserTokensSince(ctx context.Context, arg SumUserTokensSinceParams) (SumUserTokensSinceRow, error) {
	row := q.db.QueryRow(ctx, sumUserTokensSince, arg.UserID, arg.CreatedAt)
	var i SumUserTokensSinceRow
	err := row.Scan(&i.TokensIn, &i.TokensOut)
	return i, err
}
